// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD_EDI_BE.Models;

public partial class ESDMachine
{
    [Key]
    public long MachineId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string MachineCode { get; set; }

    [StringLength(255)]
    public string MachineName { get; set; }

    [StringLength(255)]
    public string ImageName { get; set; }

    public long? LocationId { get; set; }

    public long? MachineStatus { get; set; }

    public long? SupplierId { get; set; }

    public bool? isActived { get; set; }

    [Precision(3)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(3)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }
}