// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD_EDI_BE.Models;

public partial class PPORTAL_QUAL02_POLICY
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ITEM_CODE { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TRAND_TP { get; set; }

    public int CTQ_NO { get; set; }

    [Column(TypeName = "decimal(9, 3)")]
    public decimal MIN_VALUE { get; set; }

    [Column(TypeName = "decimal(9, 3)")]
    public decimal MAX_VALUE { get; set; }

    [Required]
    public bool? isActived { get; set; }

    [Precision(3)]
    public DateTime createdDate { get; set; }

    public long createdBy { get; set; }

    [Precision(3)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }
}